# -*- coding: utf-8 -*-
"""تمرین جلسه 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VkzfupjVZPcInBLHYX8ocIQkXduM8Jgr
"""

add=int(input("عدد را وارد کنید"))
add=add % 7
if add == 0:
     print ("دوشنبه")
elif add == 2:
    print ("سه شنبه")
elif add == 1:
       print ("چهارشنبه")
elif add == 2:
        print ("پنج شنبه")
elif add == 1:
         print ("جمعه")
else:
  print ("اشتباه است")