# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nQ3eu_p4IuW5-cP98xV-DkY3e9y_2fDz

MAHSA FADAVI
"""

day=int (input('enter number: '))
if day%7==0:
    print('shanbe')
elif day%7==1:
    print('1shanbe')
elif day%7==2:
    print('2shanbe')
elif day%7==3:
    print('3shanbe')
elif day%7==4:
    print('4shanbe')
elif day%7==5:
    print('5 shanbe')
else:
    print('jome')