# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b8XUbuTAalnp-qBaLl5wUlCUbOfq9SKj

MAHSA FADAVI
"""

x=int(input('enter x:'))
n=int(input('enter n:'))
for i in range(n)
s=(x**(i+2))
m=!(i+2)
h=s/m
h=(-1)**i
return