# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NquWceWXsUUyJnw0f4WmJwAUWuxfcL6K

MAHSA FADAVI
"""

import random

def generate_array(n):
    array = []
    for _ in range(n):
        array.append(random.randint(0, 100))
    return array

def print_min_max(array):
    min_value = min(array)
    max_value = max(array)
    print("Minimum value:", min_value)
    print("Maximum value:", max_value)

def print_second_min_max(array):
    sorted_array = sorted(array)
    second_min_value = sorted_array[1]
    second_max_value = sorted_array[-2]
    print("Second minimum value:", second_min_value)
    print("Second maximum value:", second_max_value)

def reverse_array(array):
    reversed_array = array[::-1]
    print("Reversed array:", reversed_array)

def print_average(array):
    average = sum(array) / len(array)
    print("Average:", average)

n = int(input("Enter the number of elements in the array: "))
array = generate_array(n)

print("Array:", array)
print_min_max(array)
print_second_min_max(array)
reverse_array(array)
print_average(array)